spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trainbooking_db
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
